import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Provider from "@/GlobalStyles/Provider";

const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning={true}>
      <body
        suppressContentEditableWarning={true}
        style={{
          minHeight: "100vh",
          backgroundColor: "black",
        }}
        className={inter.className}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
